spring.application.name=flightservice
server.port=9090
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://flightmysqlserver.cbw86wkkq71p.ap-south-1.rds.amazonaws.com:3306/flightdb?createDatabaseIfNotExist=true
spring.datasource.username=admin
spring.datasource.password=root1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
